[[section-introduction-and-goals]]
== Introduction and Goals


[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

The aim is to create an application called Radarin, a project in which the students of the Software Architecture course in the University of Oviedo are enrolled.

The members of the team are:

* Héctor Díaz Beltrán  uo269787
* Marcos Fernández González  uo270803
* Luis Fernández Suárez  uo271405
* Andrea García Cernuda  uo270115
* Sara Rubín Estrada-Nora  uo270185

What is Radarin? 

Radarin is a system to facilitate meetings between friends using new technologies.

To carry out the project's aim, the application needs the location of the users. They must voluntarily activate it and allow the application to use it. It also needs the users to have a SOLID <<solid>> pod <<pod>>, whose URL will be asked to log in. A notification will be sent in case some SOLID <<solid>> friend has accessed Radarin and is nearby too, so they can get in contact. There is a possibility of sending messages to those friends that are nearby.


=== Requirements Overview


[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

[options="header"]
|===
| Requirement | Description
| Two software components (at least) to take into account | Give the user the possibility of accessing the application through a web browser and through the mobile phone.
| Web application | It will run in a server and will store locations.

                    It will allow the users to manage and visualize locations. 
                    
                    It will also include admin options to manage users and monitor server status.
| Application run in users' mobile phone | It will send the corresponding locations to the server.

                                            It will receive notifications from nearby friend users.
| Application that runs in a server | It will store the minimal information needed about a user: the locations taken from the browser or phone and the timestamp in which those locations take place (all of them saved in the users's pods <<pods>>). The last user location is saved in the corresponding database.
                                      
                                      The rest of users' information, such as friends, locations and tags will be queried to the pods <<pods>>.
                                      
                                      No personal information will be stored in a centralized way.
| System compatibility | The system will be compatible with the SOLID project <<solid>>.
| System deployment | The system will be deployed from docker containers <<docker>>.

                      It will also be deployed in a cloud service like heroku <<heroku>>, the one finally chosen.
| Testing | Unit tests, acceptance tests and loading tests will be made.
| Continuous integration server <<contint>> | The previous tests will be automatically run on it except from loading tests.
|===

All those specifications where provided https://arquisoft.github.io/course2021/labAssignmentDescription.html[here].


=== [[quality]]Quality Goals


[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

[options="header"]
|===
|Nr|Quality|Motivation
| 1 | Usability | The application must be easy to use. Users should understand how to use it at first sight.
| 2 | Security | The use of the application must not lead to any security problem. Users must have all their personal data in a secure system. This is achieved by applying SOLID with their pods.
| 3 | Privacy | Data from users must be specifically used for the main purpose of the application. No data will be provided to third parties. Data will be decentralized, by storing it in pods.
| 4 | Mantainability | The application must be well coded so that changes in the future will be easily done without touching many parts of the code.
| 5 | Availability | The application must be accesible the 24 hours of the day.
|===


=== Stakeholders


[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****


The following table has the most important roles for the application:

[options="header"]
|===
|Role/Name|Goal/Boundaries
| Developers | Developing this application will help us learn more features about software engineering. It will also help us to improve our group work skills.
| Teachers |  They will supervise the development team by giving them some steps they have to follow and some tips in order to make the project.
| Other developers / classmates | They can provide some support to the development team by giving them advice and knowledge.
| Software engineers | Specialized people can guide developers by giving them professional advice based on their experience and studies.
| Admin | He/she manages users and monitors server status through the Web application.
| People with access to new technlogies | They would like to use this application whenever they hang around to meet their friends.
| SOLID creators / inrupt | They are interested in having a SOLID application system. 

                            They could find different bugs or problems users may have, thus improving their application. 
|===

