[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.
****

- Client: normal user who has the web application in his/her electronic device browser.
- Admin: special user who can access the system through the web application for management purposes. There is a unique admin account known for all team members. It was manually added to the mongo database to avoid security problems as third-parties knowing its credentials.
- Web App: its purpose is to gather all needed information from the database and PODs <<pods>>, through the Rest API <<rest>>. It also offers an administration interface apart from the basic functionality.
- Database: stores the minimal information needed by the app to work (locations, timestamps, webIDs and authentication keys).
- SOLID <<solid>> Server: an external server where user PODs <<pods>> are stored. The web application, using the WebIDs, is able to access specific PODs <<pods>> when needed, getting the user information without storing it elsewhere, and therefore maintaining user privacy.

=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.
****

[plantuml, diagram-business, svg]
....
:User: as user
[Radarin] << System >> as WAPI

database Users << System >> as DB {
    folder "User WebID" as foldb {
        file "Location & Timestamp" as loctmp
    }
}

cloud "SOLID server provider" {
    package "User pod" as pod {
        file "Friends" as friends
        file "Past locations and timestamps"
    }
}

note right of foldb
    May also need to
    store Auth credentials
end note

user --> WAPI : sends location
WAPI --> user : receives nearby friends and locations history
WAPI --> DB : stores current location
WAPI <-- DB : retrieves nearby friends 
pod --> WAPI : sends back friends and locations history
pod <-- WAPI : asks for friends and locations history
....

=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

[plantuml, diagram-technical, svg]
....
actor Client
actor/ Admin
cloud cloud {
component WebApp
component RestAPI
database MongoDB
}
Client -- WebApp
Admin -- WebApp
WebApp -- RestAPI : HTTP/REST
RestAPI -- MongoDB : REST
node SolidServer {
storage POD
}
WebApp -- SolidServer : HTTP
....

The most used protocol is HTTP <<http>>. 

Rest API <<rest>> communicates the application with the database as a source of information, making this interchange of information more secure. 

The web application is in charge of connecting the users, the Rest API and the PODs <<pods>>. 
