[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.
****


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.
****

**<Diagram or Table>**

**<optionally: Explanation of external domain interfaces>**

- Client: normal user who has installed the application in their mobile phone.
- Admin: special user who can access the system through the web application for management purposes.
- Mobile App: the application clients interact directly with. It relies on the web application to work as server for it.
- Web App: its purpose is to gather all needed information from the database and PODs, through the Rest API, to be able to send it to the mobile app. It also offers an administration interface. 
- Database: stores the minimal information needed by the app to work (locations, timestamps, webIDs and authentication keys).
- SOLID Server: an external server where user PODs are stored. The web application, using the WebIDs, is able to access specific PODs when needed, getting the user information without storing it elsewhere, and therefore maintaining user privacy.

=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

**<Diagram or Table>**

@startuml
actor Client
actor/ Admin
component MobileApp
Client -- MobileApp
cloud cloud {
component WebApp
component RestAPI
database DB
}
Admin -- WebApp
MobileApp -- WebApp : HTTP
MobileApp -- RestAPI : HTTP/REST
WebApp -- RestAPI : HTTP/REST
RestAPI -- DB : REST
node SolidServer {
storage POD
}
RestAPI -- SolidServer : HTTP/REST
@enduml

**<optionally: Explanation of technical interfaces>**

The most used protocol is HTTP. Rest API communicates the application with the sources of information (database and PODs), making every interchange of information more secure. 

**<Mapping Input/Output to Channels>**


