[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Interaction with user's pod

==== Adding or giving information to the pod (tags as example)

[plantuml,"adding-info-pod",svg]
....
actor John as u
participant WebApp as wa
database "John's Pod" as jpod

u -> wa : create tag
activate wa

wa -> jpod : store tag
wa -> u : show new tag in list

deactivate wa
....

==== Retrieving data from the pod

[plantuml,"retrieve-pod-data",svg]
....
actor John as u
participant WebApp as wa
database "John's Pod" as jpod

activate wa

jpod -> wa : retrieve information

wa -> u : information response

deactivate wa
....

=== User sends location

[plantuml,"user-sends-location",svg]
....
actor Bob as u
participant WebApp as wa
database DB as db
database "Bob's Pod" as bpod

u -> wa : send location and timestamp
activate wa

wa -> db : overwrite old location and timestamp
wa -> bpod : store log of location and timestamp

wa -> u : confirmation response

deactivate wa
....


=== App asks for nearby users

[plantuml,"sequence-ask-friend-nearby",svg]
....
actor Alice as u
participant WebApp as wa
database DB as db
database "Alice's Pod" as apod

u -> wa : ask for nearby friends

activate wa
wa -> u : ask for location


ref over u, wa, db, apod: send location

wa -> apod : ask for friends
apod -> wa : return friends' uri
wa -> db : ask for friends' location
db -> wa : nearby friends
wa -> u : nearby friends
deactivate wa
....
