[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[plantuml, diagram-deployment, svg]
....
@startuml
rectangle "<<cloud>>" as Cloud {
node WebApp
database MongoDB
  }
rectangle "SOLID Server" as SOLID_Server {
storage POD
  }
rectangle Browser

Smartphone --> WebApp : connects
WebApp --> SOLID_Server : uses
@enduml
....

Motivation::

Radarin is located in a cloud service (Heroku <<heroku>>), as well as the mongo database it uses. Users can access through the browser to the web application with a smartphone or tablet. Radarin connects to a SOLID <<solid>> provider, which manages the PODs <<pods>> that can be in any SOLID <<solid>> server. The three available providers are: Inrupt <<inrupt>> (the common one), SolidCommunity and SolidWeb.

Quality and/or Performance Features::

Being a web application, a network connection is needed in order for it to work. However, the app itself should not consume much bandwidth, as it does not perform heavy tasks (just sends coordinates and timestamp and receives the list of friends' webIDs and their location).  
The availability of the servers where the SOLID <<solid>> PODs <<pods>> are stored will also be key in the availability of the application itself. Implementing a cache where the friends are stored is a good idea that will be taken into account. The cache will make the app less reliant on the PODs <<pods>> availability, but it will still be necessary to have the option to manually force checking them again in case there are changes. 

Mapping of Building Blocks to Infrastructure::

The blocks that compose the system are:

- The device used by the user and the administrator to enter in a browser as it is the wy to enter in the web application.
- The web application.
- The server where the web application is located.
- The database used by the app.
- The POD <<pods>> server where all PODs <<pods>> are stored. 
- The user's PODs <<pods>>.
