[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[plantuml, diagram-deployment, svg]
....
@startuml
rectangle "<<cloud>>" as Cloud {
node WebApp
node RestApi
node Prometheus
node Grafana
database MongoDB
}
rectangle "SOLID Server" as SOLID_Server {
storage POD
}
rectangle Browser

Browser --> WebApp : connects
WebApp --> SOLID_Server : uses
WebApp --> Grafana : links to
WebApp --> Prometheus : embeds
WebApp --> RestApi : uses
Grafana --> Prometheus : uses
Prometheus --> RestApi : uses
RestApi --> MongoDB : uses
@enduml
....

Motivation::

Radarin is located in a cloud service (Heroku <<heroku>>), while the Mongo database it uses is in Mongo Atlas. Users can access through the browser to the web application with a computer or a mobile device. Radarin connects to a SOLID <<solid>> provider, which manages the PODs <<pods>> that can be in any SOLID <<solid>> server. The three available providers are: Inrupt <<inrupt>> (the most common one), SolidCommunity and SolidWeb.

Quality and/or Performance Features::

Being a web application, a network connection is needed in order for it to work. However, the app itself should not consume much bandwidth, as it does not perform heavy tasks (just sends coordinates and timestamp and receives that information with the list of friends' webIDs, their location and tags).  
The availability of the servers where the SOLID <<solid>> PODs <<pods>> are stored will also be key in the availability of the application itself. Implementing a cache where the friends are stored is a good idea that could be done as a further improvement, it could not be implemented due to the lack of time. The cache would make the app less reliant on the PODs <<pods>> availability, but it would still be necessary to have the option to manually force checking them again in case there are changes. 

Mapping of Building Blocks to Infrastructure::

The blocks that compose the system are:

- The device used by the user and the administrator to enter in a browser as it is the way to enter in the web application.
- The web application.
- The REST api used by the web application.
- The monitoring stack: prometheus and grafana to monitor the REST api
- The servers where the web application, REST api, prometheus and grafana are located.
- The database used by the REST api.
- The POD <<pods>> server where all PODs <<pods>> are stored. 
- The user's PODs <<pods>>.

Different environments::

All the blocks that compose the system could be run in the same machine, in different ones or a mixture. The monitoring stack, grafana and prometheus are not needed to run end to end testing, which means that in CI and for e2e test development deploying them is not needed. A local SOLID server is deployed for e2e testing and CI instead of using one by external providers.
