[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
Choices::
In this project the main constraint is to make the application work as a Web App. To fulfill this we have to choose technologies. SOLID <<solid>> has to be used for the webapp as it is also a constraint. React <<react>> was chosen to develop it and this decision was made for two main reasons: its compatibility with SOLID <<solid>>, and the features it offers, that we think make our task much easier.
Problems::
One problem we face when choosing the technologies is that, even though we looked into them and analyzed them, we are not familiar with them. We believe in our choices and the power of decision of the group, that contrasted these technologies with others, concluding in the decisions mentioned before. 
Solutions::
In order to solve the problem mentioned before, what we have done is work on the basics of the new technologies, getting a lot of practice and ask questions to other members of the team, as facing issues together is much easier and a lot more enriching for all the members.

=== Not create a mobile application

==== Status

Accepted

==== Context

The mobile application was a requirement for the project, but creating one in the current SOLID ecosystem was far harder than we expected. We didn't manage to create a prototype that was able to log in to a pod, something that was required to confirm the user identity.

==== Decision

Don't develope a native mobile application.

Focus on adding all the functionality to the webapp.

==== Consequences

Users don't enjoy the benefits of a mobile app.

No need to deal with react-native.

=== Restapi basic security

Giving the restapi a complete and strong security is not something easy and it takes time to carry it out. As we do not have that amount of time, only a bit, the final decision made is to give the restapi a very basic security. It consists in blocking requests different from the heroku <<heroku>> apps (restapi <<restapi>>, webapp, prometheus <<prometheus>> and grafana <<grafana>>) where the web application is deployed and localhost (with port 3000 and 5000/api) ones that are the local working pages. All that is accomplished by usind CORS <<cors>>. 

=== Prometheus and Grafana

As one of the high level requirements is monitoring the deployed web application system, we decided to use prometheus <<prometheus>> to take data every five seconds and grafana <<grafana>> to show that data in a nice looking way. 

As the team was able to deploy both of them in heroku <<heroku>>, their links were added to the admin options. The prometheus <<prometheus>> page was been embedded inside the web application instead of opening it in a new window. Grafana <<grafana>> has not been shown in the same way. The first approach was to embed it too but it does not work because a security problem, the browser tolds the user to open it in a new window, so instead of embedding it when the grafana <<grafana>> link is clicked a new window with it is openned.

=== Optional features

==== Nearby friends

A friend is considered to be nearby when the distance between him/her and the user is at most 1000 meters and the friend location updatedAt field is at most fifteen minutes ago comparing it with the current time. That last check is made because a case we are going to explain now. Imagine that a user uses the web application three days ago (updatedAt field) and the last location saved is inside the distance range but when another user, friend of the previous, uses the web application he/she sees that the friend is nearby. It could be ok or not, almost for sure the friend is not still there.

How can the users know that they have nearby friends? 

There are several possibilities, the first one is that the user has an option to see the complete list of friends, apart from the nearby ones. 

The second is that in the main map (the first one) the user can see his/her location (represented with a blue pushping) and the nearby friends locations (represented with a red pushpin, if the user clicks on them the webId of the friend is displayed to know which friend is it).

The third one is explained in the next section. 

==== Notifications

When a nearby friend is detected a pop up notification is shown in the web application apart from the notifications view where all notifications can be seen.

==== Messages



==== Google Maps library

As the web application has three different maps to show and display different information the development team had considered which frameworks or library were needed. 

Leaflet <<leaflet>> was taken into account but finally discarded because google maps <<google-maps-api>> seems to be easier to use.

The first map approach had used google-maps-react framework but as it last updated was one year ago the code does not work as expected because "was not compatible" with the framework.

That is why we changed and now we are usign @react-google-maps/api that it last updated was three months ago and with this the expected result can be achieved.

==== Visualize location made

As the user location is updated every 2 minutes, the user can see the location history in a table (MyLocations). He/she has the options to delete the desired location or to delete all locations saved in the pod <<pods>>. 

That location history is also shown in a map (LocationMap). We have to mention that the locations map does not show every recorder locations. Those that are in a range of less than 100 meters from other location is not shown, since they are not very representative and affect performance.

Imagine the situation where the user is using the web application or the development team is testing it. If they are not changing the location, every 2 minutes a new yellow pushpin is placed in the map in the same place where other marker is.

=== Tag location to facilitate their search

The users have the posibility to create tags with a name and an optional description from the location they are in that moment.

The list of created tags can be seeing apart from deleting the desired ones. Also, they can search a concrete tag by a complete or partial name if they do not find at first sight from a huge tag list.

There is a tag map where the all tags can be seen with a purple pushpin. If the user clicks in any marker, all are displayed showing the corresponding name and description (if there is).

This functionality is very useful. It is very common that people is at one local, for example a bar, that they really like but they forget or do not know its name or its address, so when the people are at that place they can use the web app to create a tag with the current location. With that tag created and with a meaningful name they can easily search for that bar location in the map.
