[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
Choices::
In this project the main constraint is to make the application work as a Web App. To fulfill this we have to choose technologies. SOLID <<solid>> has to be used for the webapp as it is also a constraint. React <<react>> was chosen to develop it and this decision was made for two main reasons: its compatibility with SOLID <<solid>>, and the features it offers, that we think make our task much easier.
Problems::
One problem we face when choosing the technologies is that, even though we looked into them and analyzed them, we are not familiar with them. We believe in our choices and the power of decision of the group, that contrasted these technologies with others, concluding in the decisions mentioned before. 
Solutions::
In order to solve the problem mentioned before, what we have done is work on the basics of the new technologies, getting a lot of practice and ask questions to other members os the team, as facing issues together is much easier and a lot more enriching for all the members.

=== Don't create a mobile application

==== Status

Accepted

==== Context

The mobile application was a requirement for the project, but creating one in the current SOLID ecosystem was far harder than we expected. We didn't manage to create a prototype that was able to log in to a pod, something that was required to confirm the user identity.

==== Decision

Don't develope a native mobile application.

Focus on adding all the functionality to the webapp.

==== Consequences

Users don't enjoy the benefits of a mobile app.

No need to deal with react-native.