[[section-technical-risks]]
== Risks and Technical Debts


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****

We will show a list of the technical risks or technical debts of the project, ordered by priority.

	* Lack of time: one of the problems we may have is that we do not have time enough for working on the project due to other subjects.
	* Lack of experience doing this type of projects: none of the members of the group are used to do this kind of projects starting from scratch. 
	* Understanding new applications: we have to learn about new applications and technologies because we have never used them before.
	* The solid ecosystem is still evolving, with key elements like authentication still being in a draft state and documentation being sparse.